functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Сайт должен иметь мобильную версию
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Сайт должен быть доступен на различных устройствах
non-functional:
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
implicit:
  - Пользователь должен иметь возможность зарегистрироваться
  - Пользователь должен иметь возможность пройти аутентификацию
  - При переключении языка должен переводиться абсолютно весь текст (за исключением наименования товара)
  - При переключении языка валюта должна изменяться соответственно
  - При добавлении товара в корзину должна быть возможность указания количества единиц товара, либо изменение количества единиц уже в корзине
  - При прокрутке витрины товара должна быть закреплена сверху строка с корзиной
  - Кнопка добавления товара в корзину не должна уезжать за пределы карточки товара (TC Reusable Silicone Magic Washing Gloves)
  - В карточке товара приналичии нескольких фотографий должна быть возможность каждую фотографию увеличить и просмотреть
  - В корзине в табличной части необходимы заголовки столбцов и выравнивание по центру по столбцу Количество
  - Сайт должен запрашивать данные пользователя для подтверждения и отправления товара (ФИО, телефон, адрес)
  - При оплате товаров картой, сайт должен запрашивать данные карты