functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность продолжить выбирать товары в каталоге после добавления товара в корзину 
  - Пользователь должен иметь возможность удалить товар из корзины
  - По завершении выбора товара должно происходить оформление заказа с переходом на страницу оплаты
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть SPA-приложением, которое не перезагружает страницу
  - Сайт должен иметь мобильную версию
  - Сайт должен быть доступен на различных устройствах
  - Корзина должна храниться в сессии браузера
implicit:
  - Плашка Hexlet Store должна перенаправлять на главный экран
  - При переключении языка должен переводиться абсолютно весь текст (за исключением наименования товара)
  - При переключении языка валюта должна изменяться соответственно
  - Иконки (соответствующие стране флаги) у обоих языков должны быть загружены
  - Поиск товаров по ключевому слову и категории должен производиться среди всех товаров со всех страниц
  - Поиск товаров по категории должен содержать значения со всех страниц
  - Поиск товаров по категории должен иметь возможность сбросить категорию и вернуться ко всем товарам
  - По всему сайту должна соблюдаться орфография
  - При нахождении на последней странице каталога, кнопка "Следующая" не должна отображаться, аналогично для первой страницы
  - В случае нескольких страниц, присутствует пагинация
  - При добавлении товара в корзину должна быть возможность указания количества единиц товара, либо изменение количества единиц уже в корзине
  - Кнопка добавления товара в корзину не должна вылазить за пределы карточки товара
  - В карточке товара при наличии нескольких фотографий должна быть возможность каждую фотографию увеличить и просмотреть
  - В корзине в табличной части необходимы заголовки столбцов и выравнивание по центру по столбцам
  - Сайт должен запрашивать данные пользователя для подтверждения и отправления товара (ФИО, телефон, адрес)
  - При оплате товаров картой, сайт должен запрашивать данные карты
  - При отсутствии интернета, сайт выдает соответствующее сообщение