functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории
  - Пользователь должен иметь возможность фильтровать товары
  - Сайт должен иметь мобильную версию
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины
  - Пользователь должен иметь возможность продолжить выбирать товары в каталоге после добавления товара в корзину 
  - Пользователь должен иметь возможность удалить товар из корзины
  - По завершении выбора товара должно происходить оформление заказа с переходом на страницу оплаты
  - Сайт должен быть доступен на различных устройствах
  - Корзина должна храниться в сессии браузера
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт нужно протестировать на совместимость с последними версиями браузеров
  - Сайт нужно разработать с учетом удобства использования и оптимизировать для скорости работы
  - Важно, чтобы сайт мог обрабатывать большое количество трафика
  - Сайт должен быть SPA-приложением, которое не перезагружает страницу
implicit:
  - Пользователь должен иметь возможность зарегистрироваться
  - Пользователь должен иметь возможность пройти аутентификацию
  - При переключении языка должен переводиться абсолютно весь текст (за исключением наименования товара)
  - При переключении языка валюта должна изменяться соответственно
  - Поиск товаров по ключевому слову и категории должен производиться среди всех товаров со всех страниц
  - Поиск товаров по категории должен содержать значения со всех страниц
  - Поиск товаров по категории должен иметь возможность сбросить категорию и вернуться ко всем товарам
  - Наименования и описание товаров должны быть написаны правильно, без ошибок
  - При добавлении товара в корзину должна быть возможность указания количества единиц товара, либо изменение количества единиц уже в корзине
  - При прокрутке витрины товара должна быть закреплена сверху строка с корзиной
  - Кнопка добавления товара в корзину не должна вылазить за пределы карточки товара
  - В карточке товара при наличии нескольких фотографий должна быть возможность каждую фотографию увеличить и просмотреть
  - В корзине в табличной части необходимы заголовки столбцов и выравнивание по центру по столбцам
  - Сайт должен запрашивать данные пользователя для подтверждения и отправления товара (ФИО, телефон, адрес)
  - При оплате товаров картой, сайт должен запрашивать данные карты
  - При отсутствии интернета, сайт выдает соответствующее сообщение